language: node_js
node_js:
  - "8"
  - "10"

before_install:
  - if [[ $TRAVIS_NODE_VERSION == 8 ]]; then npm i -g npm@latest; fi

script:
  - ./node_modules/.bin/eslint src/*.js test/*.js
  - npm test

cache: npm
